services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todoapp-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todoapp-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: production
      VITE_SERVER_URL: ${VITE_SERVER_URL}
    ports:
      - "3636:80"
